# Generated by Django 5.2.5 on 2025-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('note', 'Note')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed_insights', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
